fix(infra): 🐛 fix pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,6 +3,17 @@
 # Navigate to the frontend directory
 cd frontend
 
+# Check if commitlint is installed globally
+if ! command -v prettier &> /dev/null; then
+  echo "prettier not found. Installing globally..."
+  npm install -g prettier
+fi
+
+if ! command -v next &> /dev/null; then
+  echo "next not found. Installing globally..."
+  npm install -g next
+fi
+
 # Run linting and formatting checks
 npx prettier --check --config .prettierrc "**/*.{js,jsx,ts,tsx,css,json,mjs,cjs,yml,yaml}" --ignore-path .gitignore --ignore-path .prettierignore
 npx next lint
